### ISSUE TITLE
Host images locally for tests.

### ISSUE THREAD

**Issue by rasjani** [rasjani/robotframework-seleniumtestability#21]
if test running environment is not able to load the images, tests will fail as no animations or transitions are done towards missing images.

**Comment by gowthamraj198** [comment]
@rasjani Could you please explain the issue in more detail and what exactly needs to be done for this issue? Thanks!

**Comment by rasjani** [comment]
@gowthamraj198   already made the fix in https://github.com/rasjani/robotframework-seleniumtestability/commit/dc70228884e49cb1519bef5a010c1a465463248b ..

**Comment by gowthamraj198** [comment]
@rasjani Just wanted to understand what the issue is.. Good that you are already working on this.
