### ISSUE TITLE
Sometimes testability wait for just 5 seconds even it's more than that in settings

### ISSUE THREAD

**Issue by idxn** [rasjani/robotframework-seleniumtestability#31]
## Expected Behavior

  -  SeleniumTestability should wait for 30 seconds instead of 5 secs

## Actual Behavior
  - SeleniumTestability wait for  5 secs and raise a timeout exception

## Steps to Reproduce the Problem

  1. Execute the robot test file as an example below
https://pastebin.com/XRfDwR4e

## Specifications
  - selenium python package version: 3.141.0
  - SeleniumLibrary version: 4.1.0
  - SeleniumTestability version: 0.0.15
  - Operating System: Windows
  - Browser Version: Chrome 78
  - WebDriver Version: Chromedriver 78

## SeleniumTestability Log URL
https://pastebin.com/pp1NFZxc

## Robot output.xml URL
https://pastebin.com/b5j0qa5v

**Comment by idxn** [comment]
Workaround for me right now is to combine with Wait until keyword succeeds 
`Wait Until Keyword Succeeds|30 seconds|1 seconds|Wait For Testability Ready`

**Comment by rasjani** [comment]
Could you enable TRACE level logging in robot and then attach or share the SeleniumTestability.log when this happans ? 

Actual waiting is implemented with Selenium's "WebDriverWait" and if this is happening there are two reasons i can think off: WebDriverWait has some sort of bug or there's bug on how the timestr gets translated to seconds.

**Comment by idxn** [comment]
@rasjani The log attached in the ticket is already with TRACE level

**Comment by rasjani** [comment]
yeah, silly me.

I have few ideas but things still feel like this is not due to ST code.. I'll prepare some patches that try to catch this sort of behaviour and track down the root cause.
