### ISSUE TITLE
No keyword with name 'Set Storage Item' found.

### ISSUE THREAD

**Issue by dhanababum** [rasjani/robotframework-seleniumtestability#53]
Hi, Please find bellow test cases
```
*** Settings ***
Documentation     A test suite with a single test for valid login.
...
...               This test has a workflow that is created using keywords in
...               the imported resource file.
Resource          resource.robot
Library           SeleniumLibrary   plugins=SeleniumTestability;True;30 Seconds;True
Library           Collections


*** Test Cases ***
Valid Login
    Open Browser To Login Page
    Set Storage Item  ${key}    ${value}    storage_type=sessionStorage
    Success Page Should Be Open
    [Teardown]    Close Browser
```

When I run test cases I am getting bellow error
```
Valid Login :: A test suite with a single test for valid login.               
==============================================================================
Valid Login                                                           | FAIL |
No keyword with name 'Set Storage Item' found.
------------------------------------------------------------------------------
Valid Login :: A test suite with a single test for valid login.       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
```

Error log

```
2020-07-20 09:19:54,245 - SeleniumTestability - DEBUG -  **** New Session Created for SeleniumTestability  **** 
2020-07-20 09:19:54,245 - SeleniumTestability - DEBUG - __init__(<SeleniumLibrary.SeleniumLibrary object at 0x10cd5ff40>,True,30 Seconds,True,True)
```

Versions
```
robotframework==3.2.1
robotframework-seleniumlibrary==4.4.0
robotframework-seleniumtestability==1.1.0
selenium==3.141.0
```

**Comment by rasjani** [comment]
On Mobile atm so cant do much diagnostics but there's a corner case in Robot Framework itself that can cause this sort of scenario.  

If you have any other robot files that do load SeleniumLibrary without a plugin, new parameters (in this case plugin) will not be evaluated.

**Comment by rasjani** [comment]
Yeah, i went thru the code and only think i can think of that causes this is that you have multiple robot files in your run and not all of them are loading SeleniumTestability plugin.  Thus, leading to the issue like this. Can you @dhanababum  verify if this could be your issue ? 

I'd restructure the tests to have a single resource file that loads all the required libraries and load that resource file to quarantee that all of the libraries are loaded with same settings ..   

Ps. i started a discussion related to this on rf forums @ https://forum.robotframework.org/t/loading-libraries-to-global-scope/497

**Comment by rasjani** [comment]
shared test case with small changes (blank implementation of keywords) do pass for me..   Im inclined to think that this is because multiple instances of SeleniumLibrary are loaded ..   Closing
